### ISSUE TITLE
Add numeric type

### ISSUE THREAD

**Issue by tommy-b-10** [iamlouislab/supabase-types-converter#1]
Wanting to use this to convert my schema, but it's getting stuck as some of my types are 'numeric', which should translate to 'Decimal' in swift. Are you able to add this type into your deployed app? Much appreciated!

**Comment by louisab-dev** [comment]
Hey @tommy-b-10, thanks a lot for the message, I just updated the converter and it should work as expected, let me know how it goes for you so that I can close the issue.

**Comment by tommy-b-10** [comment]
Works fine for me, thanks, appreciate your time making this, simplifies the process a bunch.

**Comment by louisab-dev** [comment]
Great! Thank you for using it, closing this issue.
